config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :products
  root 'products#index'
  # devise_for :users, :controllers => { registrations: 'registrations' }
  resources :products do
  	resources :comments, only:[:create]
  end




end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string
#  url         :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class Product < ApplicationRecord
	belongs_to :user
	has_many :comments
	validates :name, presence: true
	validates :url, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    if @product.save
      redirect_to products_path, notice: "El producto fue publicado con éxito"

    else
      render 'new'
      
    end
  end

  def edit
    @product = Product.find(params[:id])

  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path, notice:'el producto se ha modificado con éxito'
    else
      render 'edit'
      
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path, notice: 'El producto ha sido eliminado correctamente'
  end

  private 
    def product_params
      params.require(:product).permit(:name,:url,:description)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
	def form_title
		@product.new_record? ? 'Nuevo producto' : 'Editar Producto'
	end
end

app/views/products/_form.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			<h1><%= form_title%></h1>

			<% if @product.errors.any? %>
				<div class="alert alert-danger">
					<ul>
						<% @product.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
						<% end %>
					</ul>
				</div>
			<% end %>



			<%= form_for @product do |form |%>
			<div class="form-group">
				<%= form.text_field :name, class: 'form-control input-lg', placeholder:'ingrese su nombre'%>
			</div>

			<div class="form-group">
				<%= form.text_field :url, class: 'form-control input-lg', placeholder:'ingrese las url'%>
			</div>

			<div class="form-group">
				<%= form.text_area :description, class: 'form-control input-lg', placeholder:'ingrese la descripción'%>
			</div>
			<div>
				<%= form.submit form_title, class: "btn btn-primary btn-lg btn-block" %>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<%= render 'form' %>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">

      <div class="products">
        <% @products.each do |product| %>
        <div class="product clearfix">
          <div class="product-details">
            <span class="product-title"><%= link_to product.name, product %></span>
            <span class="product-description"><%= product.description %></span>
          </div>

          <div class="product-comments">
            <span class="glyphicon glyphicon-comment"></span>
            <span class="comment-count"><%= product.comments.count %></span>
          </div>




        </div>
        <% end %>
      </div>
      <br><br><br><br><br><br><br><br><br><br>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<%= render 'form' %>

app/views/products/show.html.erb
<div class="product-page">
  <header class="product-header">
    <h1><%= @product.name %></h1>
    <p><%= @product.description %></p>
    <a href="<%= @product.url %>" class="btn btn-primary btn-lg" target="_blank">¡Obtenlo!</a>

    <% if user_signed_in? && @product.user == current_user %>
    <div class="actions">
      <%= link_to "<span class='glyphicon glyphicon-pencil'></span>".html_safe, edit_product_path(@product) %>
      <%= link_to "<span class='glyphicon glyphicon-trash'></span>".html_safe, @product, method: :delete, data: { confirm: "¿Estás seguro de eliminar este producto?" } %>
    </div>
    <% end %>



  </header>

  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1">
        <div class="votes">
          <h2>Votos</h2>
        </div>

        <div class="comments">
          <h2>Comentarios</h2>
          <% @product.comments.each do |comment| %>
              <div class="panel panel-default">
                <header class="panel-heading"><img src="<%= Gravatar.new("#{comment.user.email}").image_url %>" class="img-circle" /> <%= comment.user.name %></header>
                <div class="panel-body"><%= comment.body %></div>
              </div>
          <% end %>

          <% if signed_in? %>
              <%= form_for [@product, @product.comments.build] do |f| %>
              <div class="form-group">
                <%= f.text_area :body, class: "form-control", placeholder: "Agregar comentario" %>
              </div>

              <div class="actions text-right">
                <%= f.submit "Comentar", class: "btn btn-primary" %>
              </div>
              <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>