config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :products
  root 'products#index'
  # devise_for :users, :controllers => { registrations: 'registrations' }
  resources :products do
  	resources :comments, only:[:create]
  end




end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmallProyect</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <!--   <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <% if flash[:notice]%>
      <div class="alert alert-info">
        <%= flash[:notice]%>
      </div>
    <% end %> -->

<!-- 
    <p class="navbar-text pull-right">
      <% if user_signed_in? %>
        Bienvenido  <strong><%= current_user.email %></strong>.
        <%= link_to 'Editar profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Salir ", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Registrarse", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </p>
 -->















<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Product Hunt", root_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul style="display: flex; justify-content: center;align-items: center;" class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>




              <li class="dropdown">
                <a href="#" class="dropdown-toggle avatar" data-toggle="dropdown">
                  <img src="<%= Gravatar.new("#{current_user.email}").image_url %>" class="img-circle" />
                  <span class="caret"></span>
                </a>
              </li>
              <li><%= link_to "<span class='glyphicon glyphicon-plus'></span>".html_safe, new_product_path %></li>

              <ul >
                <li style="list-style:none;">
                   <%= link_to 'Editar profile', edit_user_registration_path, :class => 'navbar-link' %> | <%= link_to "Salir ", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                  
                </li>
              </ul>


            <% else %>


              <li>
                <%= link_to "Registrarse", new_user_registration_path, :class => 'navbar-link'  %> 
              </li>
              <li>
                 <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
                
              </li>
              
       

            <% end %>
          </ul>
          <form class="navbar-form navbar-right" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
          </form>
        </div><!-- /.navbar-collapse -->
      </div>
    </div>
  </div><!-- /.container -->
</nav>
















    <%= yield %>
  </body>
</html>